In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
from pydrake.all import StartMeshcat

# if you're not launching jupyter from the repo root, fix the path:
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

meshcat = StartMeshcat()
print("Meshcat:", meshcat.web_url())

INFO:drake:Meshcat listening for connections at http://localhost:7001


Meshcat: http://localhost:7001


In [3]:
import os
import numpy as np
from pydrake.all import StartMeshcat
from pydrake.multibody.tree import RevoluteJoint
from rocky.build import build_robot_diagram_two
from rocky.ilqr import ILQRController, CostParams
from rocky.dynamics import ArmParams, forward_kinematics

rng = np.random.default_rng()
enemy_config_mode = "random"  # options: "random", "default", "custom"
custom_enemy_degs = [30.0, -100.0]


# --- URDF ---
urdf = "../rocky.urdf"

# --- Build ---
bundle = build_robot_diagram_two(
    urdf_path=urdf,
    time_step=1e-3,
    gravity_vec=(0., 0., 0.),
    meshcat=meshcat,
)

plant, ctx, sim = bundle.plant, bundle.plant_context, bundle.simulator
ally, enemy = bundle.ally, bundle.enemy

W = plant.world_frame()
enemy_target_frame = plant.GetFrameByName("enemy_target")
ally_target_frame = plant.GetFrameByName("ally_target")
ally_wall_frame = plant.GetFrameByName("wall", model_instance=ally)
ally_glove_frame = plant.GetFrameByName("glove", model_instance=ally)
enemy_wall_frame = plant.GetFrameByName("wall", model_instance=enemy)
enemy_elbow_frame = plant.GetFrameByName("elbow_marker", model_instance=enemy)
enemy_glove_frame = plant.GetFrameByName("glove", model_instance=enemy)


ally_act_idxs = list(plant.GetJointActuatorIndices(ally))
enemy_act_idxs = list(plant.GetJointActuatorIndices(enemy))


# --- Joint helpers ---
def get_revolute_joints_for_instance(plant, instance):
    joints = [plant.get_joint(j) for j in plant.GetJointIndices(instance)]
    return [j for j in joints if isinstance(j, RevoluteJoint)]


def set_angles_for_instance(plant, ctx, instance, angles_rad):
    revs = get_revolute_joints_for_instance(plant, instance)
    for j, q in zip(revs, angles_rad):
        j.set_angle(ctx, float(q))


def set_zero_torques(plant, ctx):
    plant.get_actuation_input_port().FixValue(ctx, np.zeros(plant.num_actuators()))


def get_ally_state(plant, ctx, ally):
    q = plant.GetPositions(ctx, ally)[:2]
    dq = plant.GetVelocities(ctx, ally)[:2]
    return np.hstack([q, dq])


def get_enemy_state(plant, ctx, enemy):
    q = plant.GetPositions(ctx, enemy)[:2]
    dq = plant.GetVelocities(ctx, enemy)[:2]
    return np.hstack([q, dq])


def get_shoulder_in_world(plant, ctx, wall_frame):
    X_W_wall = plant.CalcRelativeTransform(ctx, W, wall_frame)
    shoulder_in_wall = np.array([0.0, 0.0, 1.0])   # joint origin in wall frame
    return X_W_wall.translation() + X_W_wall.rotation().matrix() @ shoulder_in_wall


def express_point_in_wall_2d(plant, ctx, wall_frame, p_W_point, p_W_shoulder):
    X_wall_W = plant.CalcRelativeTransform(ctx, wall_frame, W)
    p_wall_point = X_wall_W.multiply(p_W_point)
    p_wall_shoulder = X_wall_W.multiply(p_W_shoulder)
    rel = p_wall_point - p_wall_shoulder             # [dx, dy, dz] in wall frame
    return np.array([rel[0], rel[2]])                # model x,z  (no sign flip)


def get_ally_shoulder_in_world(plant, ctx, ally_wall_frame):
    return get_shoulder_in_world(plant, ctx, ally_wall_frame)


def get_enemy_shoulder_in_world(plant, ctx, enemy_wall_frame):
    return get_shoulder_in_world(plant, ctx, enemy_wall_frame)


def get_target_pos_2d(plant, ctx):
    p_W_shoulder = get_ally_shoulder_in_world(plant, ctx, ally_wall_frame)
    p_W_T = plant.CalcRelativeTransform(ctx, W, enemy_target_frame).translation()
    return express_point_in_wall_2d(plant, ctx, ally_wall_frame, p_W_T, p_W_shoulder)


def get_enemy_pos_2d(plant, ctx):
    p_W_shoulder = get_ally_shoulder_in_world(plant, ctx, ally_wall_frame)
    p_W_EE = plant.CalcRelativeTransform(ctx, W, enemy_glove_frame).translation()
    return express_point_in_wall_2d(plant, ctx, ally_wall_frame, p_W_EE, p_W_shoulder)


def get_enemy_target_pos_2d_for_enemy(plant, ctx):
    p_W_shoulder = get_enemy_shoulder_in_world(plant, ctx, enemy_wall_frame)
    p_W_T = plant.CalcRelativeTransform(ctx, W, ally_target_frame).translation()
    return express_point_in_wall_2d(plant, ctx, enemy_wall_frame, p_W_T, p_W_shoulder)


def get_ally_pos_2d_for_enemy(plant, ctx):
    p_W_shoulder = get_enemy_shoulder_in_world(plant, ctx, enemy_wall_frame)
    p_W_ally = plant.CalcRelativeTransform(ctx, W, ally_glove_frame).translation()
    return express_point_in_wall_2d(plant, ctx, enemy_wall_frame, p_W_ally, p_W_shoulder)


def get_ally_pos_2d_from_model(x, params):
    return forward_kinematics(x[:2], params)


def get_enemy_pos_2d_from_model(x, params):
    return forward_kinematics(x[:2], params)


def apply_combined_torques(u_ally=None, u_enemy=None):
    tau = np.zeros(plant.num_actuators())
    if u_ally is not None:
        tau[ally_act_idxs[0]] = u_ally[0]
        tau[ally_act_idxs[1]] = u_ally[1]
    if u_enemy is not None:
        tau[enemy_act_idxs[0]] = u_enemy[0]
        tau[enemy_act_idxs[1]] = u_enemy[1]
    plant.get_actuation_input_port().FixValue(ctx, tau)


def apply_ally_torque(plant, ctx, ally, u2):
    apply_combined_torques(u_ally=u2, u_enemy=None)


def apply_enemy_torque(plant, ctx, enemy, u2):
    apply_combined_torques(u_ally=None, u_enemy=u2)


def apply_enemy_torque(plant, ctx, enemy, u2):
    tau = np.zeros(plant.num_actuators())
    idx = list(plant.GetJointActuatorIndices(enemy))
    tau[idx[0]] = u2[0]
    tau[idx[1]] = u2[1]
    plant.get_actuation_input_port().FixValue(ctx, tau)


def randomize_enemy_configuration(
    clearance_buffer=0.02,
    clearance_target=None,
    clearance_ally=None,
    max_tries=200,
):
    """Sample random enemy joint angles that keep the glove away from target/ally."""
    glove_radius = 0.05
    target_radius = 0.03
    clearance_target = clearance_target or (glove_radius + target_radius + clearance_buffer)
    clearance_ally = clearance_ally or (2 * glove_radius + clearance_buffer)

    joints = get_revolute_joints_for_instance(plant, enemy)
    limits = []
    for j in joints:
        lo = j.position_lower_limit()
        hi = j.position_upper_limit()
        if not np.isfinite(lo):
            lo = -np.pi
        if not np.isfinite(hi):
            hi = np.pi
        limits.append((lo, hi))

    for attempt in range(1, max_tries + 1):
        candidate = np.array([rng.uniform(lo, hi) for lo, hi in limits])
        set_angles_for_instance(plant, ctx, enemy, candidate)

        p_enemy = plant.CalcRelativeTransform(ctx, W, enemy_glove_frame).translation()
        p_target = plant.CalcRelativeTransform(ctx, W, enemy_target_frame).translation()
        p_ally = plant.CalcRelativeTransform(ctx, W, ally_glove_frame).translation()
        p_elbow = plant.CalcRelativeTransform(ctx, W, enemy_elbow_frame).translation()
        wall_x = plant.CalcRelativeTransform(ctx, W, enemy_wall_frame).translation()[0]

        if not (p_elbow[0] < wall_x and p_enemy[0] < wall_x):
            continue
        if np.linalg.norm(p_enemy - p_target) < clearance_target:
            continue
        if np.linalg.norm(p_enemy - p_ally) < clearance_ally:
            continue
        print(f"Enemy randomized in {attempt} tries.")
        return candidate

    raise RuntimeError("Failed to sample a collision-free enemy configuration")


params = ArmParams()
cost = CostParams(
    Q=np.diag([2.0, 2.0, 0.1, 0.1]),
    R=0.01 * np.eye(2),
    Qf=np.diag([50.0, 50.0, 1.0, 1.0]),
    target_weight=425.0,
    r_min=0.01, # Turning off Exponential Cost at a certain distance
    avoid_weight=30.0,
    avoid_sigma=0.08,
)

dt_mpc = 0.02  # CHANGED: 0.05 is too large for stable feedback on this arm
horizon = 50   # Adjusted horizon to match new dt (40 * 0.02 = 0.8s lookahead)

ctrl = ILQRController(
    horizon=horizon,
    dt=dt_mpc,
    params=params,
    cost=cost,
    verbose=True,
)

print(ctrl)

# Ally starts from a fixed configuration for repeatability
ally_angles = np.deg2rad([45.0, -130.0])
set_angles_for_instance(plant, ctx, ally, ally_angles)

# Enemy configuration selection
if enemy_config_mode == "random":
    enemy_angles = randomize_enemy_configuration()
elif enemy_config_mode == "default":
    enemy_angles = np.deg2rad([45.0, -140.0])
elif enemy_config_mode == "custom":
    enemy_angles = np.deg2rad(custom_enemy_degs)
else:
    raise ValueError(f"Unknown enemy_config_mode: {enemy_config_mode}")
print("Enemy start angles (deg):", np.rad2deg(enemy_angles))
set_angles_for_instance(plant, ctx, enemy, enemy_angles)

sim.AdvanceTo(0.0)
print("Done.")




ILQRController(
  horizon=50, dt=0.02, max_iter=60, tol=0.001, reg=0.0001, verbose=True
  params: l1=0.5, l2=0.5, m1=0.6, m2=0.5, I1=0.002, I2=0.002, damping=[0.100 0.100], gravity=0, torque_limit=[50.000 50.000]
  cost: Q=[[2.000 0.000 0.000 0.000]
 [0.000 2.000 0.000 0.000]
 [0.000 0.000 0.100 0.000]
 [0.000 0.000 0.000 0.100]], R=[[0.010 0.000]
 [0.000 0.010]], Qf=[[50.000  0.000  0.000  0.000]
 [ 0.000 50.000  0.000  0.000]
 [ 0.000  0.000  1.000  0.000]
 [ 0.000  0.000  0.000  1.000]], target_w=425.0, avoid_w=30.0, avoid_sigma=0.08, x_goal=[0.000 0.000 0.000 0.000]
  alphas=[1.0, 0.5, 0.25, 0.1, 0.05]
)
Enemy randomized in 4 tries.
Enemy start angles (deg): [ -26.32995851 -104.25716338]
Done.


In [3]:
import time

t_final = 10.0
dt_ctrl = ctrl.dt
base_avoid_weight = cost.avoid_weight
avoid_decay_time = 5.0  # seconds to significantly reduce avoidance weight
min_avoid_scale = 0.1

t = sim.get_context().get_time()
u_traj_prev = None
step = 0
mode = "mpc"  # start in MPC mode

print("Starting MPC loop...")

def has_reached_target(ally_pos, target_pos, x,
                       R_target=0.1,
                       R_ally=0.005,
                       vel_tol=0.1):

    # distance between centers in task space
    pos_err = np.linalg.norm(ally_pos - target_pos)

    # geometric contact threshold
    contact_dist = R_target + R_ally

    return pos_err <= contact_dist


while t < t_final:
    # 1) Current state
    x_current = get_ally_state(plant, ctx, ally)

    # 2) Positions
    target_pos_2d = get_target_pos_2d(plant, ctx)
    enemy_pos_2d  = get_enemy_pos_2d(plant, ctx)
    ally_pos_2d   = get_ally_pos_2d_from_model(x_current, params)

    print("target positions: ", target_pos_2d)
    print("enemy positions: ", enemy_pos_2d)
    print("ally positions: ", ally_pos_2d)

    # 3) Check for NaN in state (Simulation exploded)
    if np.any(np.isnan(x_current)):
        print("ERROR: Simulation state is NaN. Physics exploded.")
        break

    # 4) Check target hit and switch to passive mode (one-way)
    if mode == "mpc" and has_reached_target(ally_pos_2d, target_pos_2d, x_current):
        print(f"\n*** Target reached at t={t:.2f}s ***")
        print(f"ally EE pos: {ally_pos_2d}, target: {target_pos_2d}")
        print("*** Target reached; switching to passive mode ***")
        mode = "passive"

    # 5) Control law: MPC vs passive. Can change this to 'attack' / 'defense' next
    if mode == "mpc":
        # Decay enemy-avoidance weight over time
        decay = np.exp(-t / avoid_decay_time)
        avoid_scale = max(min_avoid_scale, decay)
        ctrl.cost.avoid_weight = base_avoid_weight * avoid_scale

        # MPC step
        x_pred, result = ctrl.step_mpc(
            x_current,
            target_pos=target_pos_2d,
            enemy_pos=enemy_pos_2d,
            prev_u_trj=u_traj_prev,
        )

        if np.isfinite(result.cost) and result.converged:
            u_traj_prev = result.u_trj
            u0 = result.u_trj[0]
        else:
            print(f"[Warning] iLQR failed (cost: {result.cost}, conv: {result.converged}). Braking.")
            # Damping torque to stop robot if controller fails
            u0 = params.clip_u(-2.0 * x_current[2:])
            u_traj_prev = None  # Reset warm start
    else:
        # Passive after hit: zero (or damping) torques
        # You can replace np.zeros(2) by a damping law if you want.

        # change here or new mode ==
        u0 = np.zeros(2)


    # 6) Debug prints
    if step % 5 == 0:
        if mode == "mpc":
            dbg_cost = result.cost
            dbg_avoid = ctrl.cost.avoid_weight
        else:
            dbg_cost = float("nan")
            dbg_avoid = ctrl.cost.avoid_weight  # last value from MPC phase

        print(
            f"t={t:.3f} | mode={mode} | "
            f"x={np.array2string(x_current, precision=2)} | "
            f"cost={dbg_cost:.1f} | avoid_w={dbg_avoid:.1f} | "
            f"u0={np.array2string(u0, precision=2)}"
        )

    # 7) Apply control and advance sim
    apply_ally_torque(plant, ctx, ally, u0)
    sim.AdvanceTo(t + dt_ctrl)
    t = sim.get_context().get_time()
    step += 1

print("MPC run complete.")


Starting MPC loop...
target positions:  [0.8  0.25]
enemy positions:  [0.59002448 0.14454396]
ally positions:  [0.39713126 0.14454396]
[iLQR] init cost 2395.4612
[iLQR] iter 0 alpha 0.50 -> cost 2051.7595
[iLQR] converged at iter 0 cost 2051.7595
[MPC] x=[ 0.78539816 -2.26892803  0.          0.        ], target=[0.8  0.25], u0=[-12.37426572   5.55105491], cost=2051.7595330834947
t=0.000 | mode=mpc | x=[ 0.79 -2.27  0.    0.  ] | cost=2051.8 | avoid_w=30.0 | u0=[-12.37   5.55]
target positions:  [0.8  0.25]
enemy positions:  [0.59002448 0.14454396]
ally positions:  [0.40638602 0.15364505]
[iLQR] init cost 2516.2452
[iLQR] iter 0 alpha 1.00 -> cost 885.1196
[iLQR] converged at iter 0 cost 885.1196
[MPC] x=[ 0.75989127 -2.24271303 -2.52658584  2.63861483], target=[0.8  0.25], u0=[-24.41890323   8.46379454], cost=885.1195526951954
target positions:  [0.8  0.25]
enemy positions:  [0.59002448 0.14454396]
ally positions:  [0.43976586 0.19254722]
[iLQR] init cost 747.8707
[iLQR] iter 0 alpha 0

/Users/omarh/Documents/Repos/MEAM5170/RoboRocky/rocky/ilqr.py:135: RuntimeWarning: overflow encountered in matmul
  l += 0.5 * dx.T @ cost.Q @ dx + 0.5 * u.T @ cost.R @ u
/Users/omarh/Documents/Repos/MEAM5170/RoboRocky/rocky/dynamics.py:94: RuntimeWarning: overflow encountered in matmul
  ddq = np.linalg.solve(M, u_clipped - C @ dq - G - damping)


target positions:  [0.8  0.25]
enemy positions:  [0.73662752 0.14981319]
ally positions:  [0.63318303 0.29968306]
[iLQR] init cost 1338.3549
[iLQR] iter 0 no improvement (cost 25730421603447374594122420039188480.0000)
[MPC] iLQR failed; using zero torque.
[MPC] x=[ 0.35261082 -1.58933601 -2.01876238  1.26274039], target=[0.8  0.25], u0=[0. 0.], cost=1338.3548619830053
[Warning] iLQR failed (cost: 1338.3548619830053, conv: False). Braking.
target positions:  [0.8  0.25]
enemy positions:  [0.78268887 0.13727081]
ally positions:  [0.62547392 0.31738361]
[iLQR] init cost 3821.4229
[iLQR] iter 0 alpha 1.00 -> cost 1308.0240
[iLQR] converged at iter 0 cost 1308.0240
[MPC] x=[ 0.3238754  -1.58689707 -1.06793701 -0.88020974], target=[0.8  0.25], u0=[19.40820378 14.20519695], cost=1308.0239794065951
target positions:  [0.8  0.25]
enemy positions:  [0.81682195 0.11821754]
ally positions:  [0.64673513 0.3172711 ]
[iLQR] init cost 2011.3298
[iLQR] iter 0 alpha 0.25 -> cost 1737.1752
[iLQR] converg

In [4]:
# Enemy attack controller (run this cell to let the enemy strike back)
enemy_attack_duration = 8.0

enemy_cost = CostParams(
    Q=np.diag([2.0, 2.0, 0.1, 0.1]),
    R=0.01 * np.eye(2),
    Qf=np.diag([50.0, 50.0, 1.0, 1.0]),
    target_weight=425.0,
    r_min=0.01,
    avoid_weight=30.0,
    avoid_sigma=0.08,
)

enemy_ctrl = ILQRController(
    horizon=50,
    dt=0.02,
    params=params,
    cost=enemy_cost,
    verbose=True,
)

base_enemy_avoid_weight = enemy_cost.avoid_weight
enemy_avoid_decay_time = 5.0
enemy_min_avoid_scale = 0.1
enemy_u_traj_prev = None
enemy_mode = "mpc"

enemy_t_start = sim.get_context().get_time()
enemy_t_final = enemy_t_start + enemy_attack_duration
enemy_t = enemy_t_start
enemy_step = 0
result = None

print("Starting ENEMY MPC loop...")
apply_combined_torques(u_ally=np.zeros(2), u_enemy=np.zeros(2))


def has_enemy_reached_target(enemy_pos, target_pos, x,
                             R_target=0.1,
                             R_enemy=0.005,
                             vel_tol=0.1):
    pos_err = np.linalg.norm(enemy_pos - target_pos)
    contact_dist = R_target + R_enemy
    vel_norm = np.linalg.norm(x[2:])
    return pos_err <= contact_dist and vel_norm < vel_tol


while enemy_t < enemy_t_final:
    x_enemy = get_enemy_state(plant, ctx, enemy)
    enemy_pos_2d = get_enemy_pos_2d_from_model(x_enemy, params)
    target_pos_2d = get_enemy_target_pos_2d_for_enemy(plant, ctx)
    ally_pos_2d = get_ally_pos_2d_for_enemy(plant, ctx)

    if np.any(np.isnan(x_enemy)):
        print("ERROR: Enemy state is NaN. Stopping enemy controller.")
        break

    if enemy_mode == "mpc" and has_enemy_reached_target(enemy_pos_2d, target_pos_2d, x_enemy):
        print(f"*** Enemy target reached at t={enemy_t:.2f}s ***")
        print(f"enemy EE pos: {enemy_pos_2d}, target: {target_pos_2d}")
        enemy_mode = "passive"
        enemy_u_traj_prev = None

    if enemy_mode == "mpc":
        elapsed = enemy_t - enemy_t_start
        decay = np.exp(-elapsed / enemy_avoid_decay_time)
        avoid_scale = max(enemy_min_avoid_scale, decay)
        enemy_ctrl.cost.avoid_weight = base_enemy_avoid_weight * avoid_scale

        x_pred, result = enemy_ctrl.step_mpc(
            x_enemy,
            target_pos=target_pos_2d,
            enemy_pos=ally_pos_2d,
            prev_u_trj=enemy_u_traj_prev,
        )

        if np.isfinite(result.cost) and result.converged:
            enemy_u_traj_prev = result.u_trj
            u0 = result.u_trj[0]
        else:
            print(f"[Enemy Warning] iLQR failed (cost: {result.cost}, conv: {result.converged}). Braking.")
            u0 = params.clip_u(-2.0 * x_enemy[2:])
            enemy_u_traj_prev = None
    else:
        u0 = np.zeros(2)

    if enemy_step % 5 == 0:
        if enemy_mode == "mpc" and result is not None:
            dbg_cost = result.cost
            dbg_avoid = enemy_ctrl.cost.avoid_weight
        else:
            dbg_cost = float("nan")
            dbg_avoid = enemy_ctrl.cost.avoid_weight

        print(
            f"t={enemy_t:.3f} | mode={enemy_mode} | "
            f"x={np.array2string(x_enemy, precision=2)} | "
            f"cost={dbg_cost:.1f} | avoid_w={dbg_avoid:.1f} | "
            f"u0={np.array2string(u0, precision=2)}"
        )

    apply_combined_torques(u_ally=np.zeros(2), u_enemy=u0)
    sim.AdvanceTo(enemy_t + enemy_ctrl.dt)
    enemy_t = sim.get_context().get_time()
    enemy_step += 1

apply_combined_torques(u_ally=np.zeros(2), u_enemy=np.zeros(2))
print("Enemy MPC run complete.")




Starting ENEMY MPC loop...
[iLQR] init cost 9018.2112
[iLQR] iter 0 alpha 1.00 -> cost 3904.9752
[iLQR] converged at iter 0 cost 3904.9752
[MPC] x=[-0.45954447 -1.81963077  0.          0.        ], target=[0.95 0.25], u0=[50.         18.80109386], cost=3904.975240423839
t=0.000 | mode=mpc | x=[-0.46 -1.82  0.    0.  ] | cost=3905.0 | avoid_w=30.0 | u0=[50.  18.8]
[iLQR] init cost 4953.1584
[iLQR] iter 0 alpha 0.25 -> cost 3375.7582
[iLQR] converged at iter 0 cost 3375.7582
[MPC] x=[-0.40283515 -1.75742599  5.42732254  6.38507659], target=[0.95 0.25], u0=[ 37.74509804 -13.33864972], cost=3375.75820974206
[iLQR] init cost 7970.4946
[iLQR] iter 0 alpha 1.00 -> cost 2345.6834
[iLQR] converged at iter 0 cost 2345.6834
[MPC] x=[-0.22732235 -1.73502657 11.91881676 -3.11103302], target=[0.95 0.25], u0=[-13.85022724  14.20512183], cost=2345.6833517671857
[iLQR] init cost 3636.2411
[iLQR] iter 0 alpha 0.10 -> cost 3201.0761
[iLQR] converged at iter 0 cost 3201.0761
[MPC] x=[-0.04225704 -1.641025

/Users/omarh/Documents/Repos/MEAM5170/RoboRocky/rocky/ilqr.py:135: RuntimeWarning: overflow encountered in matmul
  l += 0.5 * dx.T @ cost.Q @ dx + 0.5 * u.T @ cost.R @ u
/Users/omarh/Documents/Repos/MEAM5170/RoboRocky/rocky/dynamics.py:94: RuntimeWarning: overflow encountered in matmul
  ddq = np.linalg.solve(M, u_clipped - C @ dq - G - damping)


[iLQR] init cost 3376.1437
[iLQR] iter 0 alpha 0.50 -> cost 1573.8064
[iLQR] converged at iter 0 cost 1573.8064
[MPC] x=[ 0.12928808 -1.35963114  4.17436313  0.62303434], target=[0.95 0.25], u0=[-20.78653032 -15.44152121], cost=1573.806426460313
t=0.100 | mode=mpc | x=[ 0.13 -1.36  4.17  0.62] | cost=1573.8 | avoid_w=29.4 | u0=[-20.79 -15.44]
[iLQR] init cost 1815.2623
[iLQR] iter 0 alpha 0.05 -> cost 1810.8115
[iLQR] converged at iter 0 cost 1810.8115
[MPC] x=[ 0.2137819  -1.43039901  3.84875297 -6.90155781], target=[0.95 0.25], u0=[-18.41956306   3.92431879], cost=1810.8115006976718
[iLQR] init cost 2591.1227
[iLQR] iter 0 alpha 1.00 -> cost 1373.2263
[iLQR] converged at iter 0 cost 1373.2263
[MPC] x=[ 0.25139844 -1.49460208  0.35853265 -0.46904569], target=[0.95 0.25], u0=[7.6396394 7.1361549], cost=1373.2262700602628
[iLQR] init cost 1607.2447
[iLQR] iter 0 alpha 0.50 -> cost 804.0517
[iLQR] converged at iter 0 cost 804.0517
[MPC] x=[ 0.257755   -1.46332527  0.26431344  3.39006682]

/Users/omarh/Documents/Repos/MEAM5170/RoboRocky/rocky/ilqr.py:173: RuntimeWarning: overflow encountered in matmul
  l   = 0.5 * (x - cost.x_goal).T @ cost.Qf @ (x - cost.x_goal)


[iLQR] init cost 1341.2004
[iLQR] iter 0 alpha 0.50 -> cost 1022.2328
[iLQR] converged at iter 0 cost 1022.2328
[MPC] x=[ 0.11865948 -0.88375366 -0.03023681  0.145954  ], target=[0.95 0.25], u0=[0.49692708 1.60477033], cost=1022.232763428276
t=0.500 | mode=mpc | x=[ 0.12 -0.88 -0.03  0.15] | cost=1022.2 | avoid_w=27.1 | u0=[0.5 1.6]
[iLQR] init cost 1098.7714
[iLQR] iter 0 alpha 0.10 -> cost 1079.9263
[iLQR] converged at iter 0 cost 1079.9263
[MPC] x=[ 0.1178195  -0.88266425 -0.08169332  0.10520348], target=[0.95 0.25], u0=[ 0.18788956 -0.01537213], cost=1079.926330729521
*** Enemy target reached at t=0.54s ***
enemy EE pos: [0.85720136 0.28798218], target: [0.95 0.25]
t=0.600 | mode=passive | x=[ 0.12 -0.88 -0.02 -0.02] | cost=nan | avoid_w=27.0 | u0=[0. 0.]
t=0.700 | mode=passive | x=[ 0.11 -0.89 -0.02 -0.01] | cost=nan | avoid_w=27.0 | u0=[0. 0.]
t=0.800 | mode=passive | x=[ 0.11 -0.89 -0.02 -0.01] | cost=nan | avoid_w=27.0 | u0=[0. 0.]
t=0.900 | mode=passive | x=[ 0.11 -0.89 -0.02 