In [1]:
%load_ext autoreload
%autoreload 2

import sys, os
from pydrake.all import StartMeshcat

# if you're not launching jupyter from the repo root, fix the path:
repo_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
if repo_root not in sys.path:
    sys.path.insert(0, repo_root)

meshcat = StartMeshcat()
print("Meshcat:", meshcat.web_url())

INFO:drake:Meshcat listening for connections at http://localhost:7000


Meshcat: http://localhost:7000


In [18]:
import os
import numpy as np
from pydrake.all import StartMeshcat
from pydrake.multibody.tree import RevoluteJoint
from rocky.build import build_robot_diagram_two
from rocky.ilqr import ILQRController, CostParams
from rocky.dynamics import ArmParams, forward_kinematics



# --- URDF ---
urdf = "../rocky.urdf"

# --- Build ---
bundle = build_robot_diagram_two(
    urdf_path=urdf,
    time_step=1e-3,
    gravity_vec=(0., 0., 0.),
    meshcat=meshcat,
)

plant, ctx, sim = bundle.plant, bundle.plant_context, bundle.simulator
ally, enemy = bundle.ally, bundle.enemy

W = plant.world_frame()
enemy_target_frame = plant.GetFrameByName("enemy_target")
ally_wall_frame = plant.GetFrameByName("wall", model_instance=ally)
ally_glove_frame = plant.GetFrameByName("glove", model_instance=ally)
enemy_glove_frame = plant.GetFrameByName("glove", model_instance=enemy)

# --- Joint helpers ---
def get_revolute_joints_for_instance(plant, instance):
    joints = [plant.get_joint(j) for j in plant.GetJointIndices(instance)]
    return [j for j in joints if isinstance(j, RevoluteJoint)]


def set_angles_for_instance(plant, ctx, instance, angles_rad):
    revs = get_revolute_joints_for_instance(plant, instance)
    for j, q in zip(revs, angles_rad):
        j.set_angle(ctx, float(q))


def set_zero_torques(plant, ctx):
    plant.get_actuation_input_port().FixValue(ctx, np.zeros(plant.num_actuators()))


def get_ally_state(plant, ctx, ally):
    q = plant.GetPositions(ctx, ally)[:2]
    dq = plant.GetVelocities(ctx, ally)[:2]
    return np.hstack([q, dq])

def get_ally_shoulder_in_world(plant, ctx, ally_wall_frame):
    X_W_wall = plant.CalcRelativeTransform(ctx, W, ally_wall_frame)
    shoulder_in_wall = np.array([0.0, 0.0, 1.0])   # joint origin in wall frame
    return X_W_wall.translation() + shoulder_in_wall


def get_target_pos_2d(plant, ctx):
    p_W_shoulder = get_ally_shoulder_in_world(plant, ctx, ally_wall_frame)
    p_W_T = plant.CalcRelativeTransform(ctx, W, enemy_target_frame).translation()
    rel = p_W_T - p_W_shoulder              # [dx, dy, dz] in world
    return np.array([rel[0], rel[2]])       # model x,z  (no sign flip)


def get_enemy_pos_2d(plant, ctx):
    p_W_shoulder = get_ally_shoulder_in_world(plant, ctx, ally_wall_frame)
    p_W_EE = plant.CalcRelativeTransform(ctx, W, enemy_glove_frame).translation()
    rel = p_W_EE - p_W_shoulder
    return np.array([rel[0], rel[2]])       # model x,z  (no sign flip)



def get_ally_pos_2d_from_model(x, params):
    return forward_kinematics(x[:2], params)


def apply_ally_torque(plant, ctx, ally, u2):
    tau = np.zeros(plant.num_actuators())
    idx = list(plant.GetJointActuatorIndices(ally))
    tau[idx[0]] = u2[0]
    tau[idx[1]] = u2[1]
    plant.get_actuation_input_port().FixValue(ctx, tau)


params = ArmParams()
cost = CostParams(
    Q=np.diag([2.0, 2.0, 0.1, 0.1]),
    R=0.01 * np.eye(2),
    Qf=np.diag([50.0, 50.0, 1.0, 1.0]),
    target_weight=300.0,
    avoid_weight=300.0,
    avoid_sigma=0.12,
)

ctrl = ILQRController(
    horizon=60,
    dt=0.02,
    params=params,
    cost=cost,
    verbose=False,
)

print(ctrl)

# --- Initial angles ---

# (+ moves down, + moves down)
ally_angles = np.deg2rad([20.0, -90.0])

# (+ moves down, + moves down)
enemy_angles = np.deg2rad([40.0, -90.0]) # + moves down

set_angles_for_instance(plant, ctx, ally, ally_angles)
set_angles_for_instance(plant, ctx, enemy, enemy_angles)

sim.AdvanceTo(0.0)
print("Done.")

ILQRController(
  horizon=60, dt=0.02, max_iter=60, tol=0.001, reg=0.0001, verbose=False
  params: l1=0.5, l2=0.5, m1=0.6, m2=0.5, I1=0.002, I2=0.002, damping=[0.100 0.100], gravity=0, torque_limit=[50.000 50.000]
  cost: Q=[[2.000 0.000 0.000 0.000]
 [0.000 2.000 0.000 0.000]
 [0.000 0.000 0.100 0.000]
 [0.000 0.000 0.000 0.100]], R=[[0.010 0.000]
 [0.000 0.010]], Qf=[[50.000  0.000  0.000  0.000]
 [ 0.000 50.000  0.000  0.000]
 [ 0.000  0.000  1.000  0.000]
 [ 0.000  0.000  0.000  1.000]], target_w=300.0, avoid_w=300.0, avoid_sigma=0.12, x_goal=[0.000 0.000 0.000 0.000]
  alphas=[1.0, 0.5, 0.25, 0.1, 0.05]
)
Done.


In [19]:
import time

t_final = 10.0
dt_ctrl = ctrl.dt
t = sim.get_context().get_time()
u_traj_prev = None
dt_mpc = 0.02  # CHANGED: 0.05 is too large for stable feedback on this arm
horizon = 40   # Adjusted horizon to match new dt (40 * 0.02 = 0.8s lookahead)
step = 0

print("Starting MPC loop...")

def has_reached_target(ally_pos, target_pos, x, pos_tol=0.1, vel_tol=0.1):
    pos_err = np.linalg.norm(ally_pos - target_pos)
    return (pos_err < pos_tol)

while t < t_final:
    # 1) Current state
    x_current = get_ally_state(plant, ctx, ally)

    # 2) Positions
    target_pos_2d = get_target_pos_2d(plant, ctx)
    enemy_pos_2d  = get_enemy_pos_2d(plant, ctx)
    ally_pos_2d   = get_ally_pos_2d_from_model(x_current, params)
    
    # Check for NaN in state (Simulation exploded)
    if np.any(np.isnan(x_current)):
        print("ERROR: Simulation state is NaN. Physics exploded.")
        break

    if has_reached_target(ally_pos_2d, target_pos_2d, x_current):
        print(f"\n*** Target reached at t={t:.2f}s ***")
        print(f"ally EE pos: {ally_pos_2d}, target: {target_pos_2d}")
        print("Holding position with zero torque.")
        apply_ally_torque(plant, ctx, ally, np.zeros(2))
        sim.AdvanceTo(t + dt_ctrl)
        t = sim.get_context().get_time()
        step += 1
        break

    # 4) MPC Step
    x_pred, result = ctrl.step_mpc(
        x_current,
        target_pos=target_pos_2d,
        enemy_pos=enemy_pos_2d,
        prev_u_trj=u_traj_prev,
    )

    if np.isfinite(result.cost) and result.converged:
        u_traj_prev = result.u_trj
        u0 = result.u_trj[0]
    else:
        print(f"[Warning] iLQR failed (cost: {result.cost}, conv: {result.converged}). Braking.")
        # Damping torque to stop robot if controller fails
        u0 = params.clip_u(-2.0 * x_current[2:])
        u_traj_prev = None # Reset warm start

    # 5) Debug prints
    if step % 5 == 0: # reduce spam
        print(f"t={t:.3f} | x={np.array2string(x_current, precision=2)} | cost={result.cost:.1f} | u0={np.array2string(u0, precision=2)}")

    # 6) Apply
    apply_ally_torque(plant, ctx, ally, u0)
    
    # Advance exactly by the controller dt
    sim.AdvanceTo(t + dt_mpc)
    t = sim.get_context().get_time()
    step += 1

print("MPC run complete.")


Starting MPC loop...
t=0.000 | x=[ 0.35 -1.57 -0.09  0.4 ] | cost=6192.6 | u0=[-9.9  -0.95]
[Warning] iLQR failed (cost: nan, conv: False). Braking.
[Warning] iLQR failed (cost: 4660.562361760853, conv: False). Braking.
t=0.100 | x=[ 0.4  -1.56  1.5   0.87] | cost=4660.6 | u0=[-3.   -1.74]
[Warning] iLQR failed (cost: 5320.46659256976, conv: False). Braking.
[Warning] iLQR failed (cost: 9088.72399947496, conv: False). Braking.
t=0.200 | x=[ 0.4  -1.48 -4.17  4.01] | cost=6210.9 | u0=[ 19.38 -22.61]
[Warning] iLQR failed (cost: nan, conv: False). Braking.
t=0.300 | x=[ 0.45 -1.57  0.2  -0.03] | cost=6659.0 | u0=[-17.03  -1.92]
t=0.400 | x=[ 0.1  -1.12 -0.42  1.21] | cost=3933.9 | u0=[10.4  -4.47]
[Warning] iLQR failed (cost: nan, conv: False). Braking.
[Warning] iLQR failed (cost: nan, conv: False). Braking.
t=0.500 | x=[ 0.41 -1.22 -9.11 19.73] | cost=nan | u0=[ 18.23 -39.46]
[Warning] iLQR failed (cost: 8816.533896559864, conv: False). Braking.
[Warning] iLQR failed (cost: 5.084651878